### ISSUE TITLE
Another release

### ISSUE THREAD

**Issue by cheungnj** [pyauth/requests-http-signature#31]
Hi and thanks for working on this library!

There's a couple changes that have been merged in since the 0.2.0 release that I'd like to make use of in a project of mine.
Would it be possible to push a new release to pypi that has those changes?

Thanks again!

**Comment by georgkrause** [comment]
Hi @cheungnj !

I asked for another release in May 2021: https://github.com/pyauth/requests-http-signature/issues/22

Since then nothing changed, so I did a hard fork a few days ago, which also improves tooling and some minor things: https://dev.funkwhale.audio/funkwhale/requests-http-message-signatures

No release yet as well, but there will be in the next few days.

**Comment by kislyuk** [comment]
Thanks for your interest! I just released a new version that updates the logic to comply with the latest draft standard.

**Comment by cheungnj** [comment]
Thank you!
